spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      web-stat-filter:
        enabled: true
        url-pattern: /*
      aop-patterns: com.xtb.restful.*
      filters: stat,wall
      filter:
        stat:
          slow-sql-millis: 1000
        wall:
          enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: "123456"
#mybatis:
#  mapper-locations: classpath:mapper/*.xml





server:
  port: 8081




